### ISSUE TITLE
How it Works button

### ISSUE THREAD

**Issue by gliinbox** [WeTrustPlatform/trusted-oracle#1]
How it Works button on top of screen and in middle of the page should go to:
https://blog.wetrust.io/how-trusted-oracle-works-621546b587ad

<img width="1646" alt="Screen Shot 2019-10-01 at 9 41 36 PM" src="https://user-images.githubusercontent.com/4187502/66020834-5ba43f80-e49d-11e9-9d24-9a0b8694b743.png">

**Comment by gliinbox** [comment]
@minheq

**Comment by minheq** [comment]
updated
